version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: duochat-db
    restart: always

    environment:
      POSTGRES_DB: duochat_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
